on: push

name: check-lint-test

jobs:
  check:
    runs-on: self-hosted
    env:
      CARGO_TARGET_DIR: ${{ github.workspace }}/../target
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check

  lint:
    runs-on: self-hosted
    env:
      CARGO_TARGET_DIR: ${{ github.workspace }}/../target
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings

  test:
    runs-on: self-hosted
    env:
      CARGO_TARGET_DIR: ${{ github.workspace }}/../target
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: install ripgrep
        run: cargo install ripgrep --locked 2>/dev/null || true
      - run: cargo test
